import { Question } from "../InterviewSubjects";

// Collection of 30 most asked Computer Networks interview questions
export const computerNetworkQuestions: Question[] = [
  {
    id: "cn-1",
    question: "Explain the OSI model and its seven layers",
    category: "networking-fundamentals",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "The OSI (Open Systems Interconnection) model is a conceptual framework with 7 layers: 1) Physical Layer: transmission of raw bits over physical medium (cables, wireless). 2) Data Link Layer: node-to-node delivery, error detection/correction, MAC addresses, Ethernet. 3) Network Layer: routing between networks, IP addresses, routers. 4) Transport Layer: end-to-end delivery, TCP/UDP, flow control, error recovery. 5) Session Layer: session management, authentication, checkpointing. 6) Presentation Layer: data formatting, encryption, compression. 7) Application Layer: network services to applications, HTTP, FTP, SMTP. Each layer provides services to the layer above and uses services from the layer below, enabling modular network design.",
    tips: [
      "Use mnemonics like 'Please Do Not Throw Sausage Pizza Away'",
      "Give real-world examples for each layer",
      "Compare with TCP/IP model",
      "Explain encapsulation and de-encapsulation"
    ],
    tags: ["osi-model", "networking", "layers"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-2",
    question: "Difference between TCP and UDP protocols",
    category: "transport-protocols",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "TCP (Transmission Control Protocol) is connection-oriented, reliable, and provides ordered delivery with error checking, flow control, and congestion control. It uses 3-way handshake for connection establishment and guarantees data delivery. UDP (User Datagram Protocol) is connectionless, unreliable, and provides fast, low-overhead communication without guarantees. TCP is used for applications requiring reliability (HTTP, FTP, email), while UDP is used for real-time applications where speed matters more than reliability (video streaming, online gaming, DNS).",
    tips: [
      "Compare reliability vs speed trade-offs",
      "Give specific use case examples",
      "Explain TCP's overhead mechanisms",
      "Discuss when to choose each protocol"
    ],
    tags: ["tcp", "udp", "transport-layer"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-3",
    question: "Explain how DHCP works",
    category: "network-protocols",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "DHCP (Dynamic Host Configuration Protocol) automatically assigns IP addresses and network configuration to devices. The DORA process: 1) Discover: client broadcasts DHCP discover message. 2) Offer: DHCP server responds with IP address offer. 3) Request: client requests the offered IP. 4) Acknowledge: server confirms assignment and provides additional config (subnet mask, gateway, DNS servers). Lease time determines how long the assignment is valid. DHCP eliminates manual IP configuration and prevents IP conflicts.",
    tips: [
      "Explain the DORA process step by step",
      "Discuss lease renewal and release",
      "Mention DHCP relay agents for multiple subnets",
      "Compare with static IP assignment"
    ],
    tags: ["dhcp", "ip-assignment", "network-protocols"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-4",
    question: "What is subnetting and why is it used?",
    category: "ip-addressing",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Subnetting divides a large network into smaller subnetworks using subnet masks. It provides: 1) Better organization and management of large networks. 2) Improved security through network segmentation. 3) Reduced broadcast traffic by limiting broadcast domains. 4) More efficient use of IP address space. Subnet mask determines network vs host portions of IP address. For example, 192.168.1.0/24 means first 24 bits are network, last 8 bits are host, allowing 254 host addresses. VLSM (Variable Length Subnet Masking) allows different subnet sizes for efficient address utilization.",
    tips: [
      "Explain subnet mask notation (CIDR)",
      "Show calculation examples",
      "Discuss VLSM benefits",
      "Mention broadcast and network addresses"
    ],
    tags: ["subnetting", "ip-addressing", "vlsm"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-5",
    question: "Explain how DNS resolution works",
    category: "network-protocols",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "DNS (Domain Name System) translates domain names to IP addresses through a hierarchical process: 1) Client checks local cache. 2) If not found, queries local DNS resolver (ISP). 3) Resolver queries root name servers for TLD information. 4) Queries TLD servers for authoritative name server. 5) Queries authoritative server for actual IP address. 6) Response is cached at multiple levels for efficiency. DNS uses UDP port 53 for queries, TCP for zone transfers. Recursive queries (resolver does the work) vs iterative queries (client does the work).",
    tips: [
      "Explain the hierarchical structure",
      "Discuss caching at different levels",
      "Compare recursive vs iterative queries",
      "Mention DNS record types (A, AAAA, CNAME, MX)"
    ],
    tags: ["dns", "name-resolution", "hierarchy"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-6",
    question: "What is NAT and how does it work?",
    category: "network-protocols",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "NAT (Network Address Translation) allows multiple devices on a private network to share a single public IP address. When a device sends a packet out, NAT replaces the private source IP with the public IP and stores the mapping in a translation table. For incoming responses, NAT uses the table to forward packets to the correct internal device. Types include: Static NAT (one-to-one mapping), Dynamic NAT (pool of public IPs), and PAT/NAPT (Port Address Translation using different ports). NAT enables IPv4 address conservation and provides basic security by hiding internal network structure.",
    tips: [
      "Explain the translation table concept",
      "Discuss different types of NAT",
      "Mention limitations like peer-to-peer connectivity",
      "Compare with IPv6 approach"
    ],
    tags: ["nat", "ip-translation", "ipv4"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-7",
    question: "Explain the TCP 3-way handshake process",
    category: "transport-protocols",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "TCP 3-way handshake establishes a reliable connection: 1) SYN: Client sends SYN packet with initial sequence number to server. 2) SYN-ACK: Server responds with SYN-ACK, acknowledging client's sequence number and sending its own sequence number. 3) ACK: Client acknowledges server's sequence number. After this, both sides have confirmed each other's sequence numbers and the connection is established. This process synchronizes sequence numbers for reliable data transfer and confirms both sides are ready to communicate.",
    tips: [
      "Explain sequence number synchronization",
      "Discuss what happens if packets are lost",
      "Mention connection termination (4-way handshake)",
      "Compare with UDP's connectionless nature"
    ],
    tags: ["tcp", "handshake", "connection"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-8",
    question: "What is HTTP and explain HTTP methods",
    category: "application-protocols",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "HTTP (HyperText Transfer Protocol) is an application-layer protocol for web communication. Common methods: GET (retrieve data, idempotent, cacheable), POST (submit data, not idempotent, may have side effects), PUT (update/create resource, idempotent), DELETE (remove resource, idempotent), PATCH (partial update), HEAD (like GET but only headers), OPTIONS (check allowed methods). HTTP is stateless - each request is independent. HTTPS adds TLS encryption for security.",
    tips: [
      "Explain idempotency concept",
      "Discuss status codes (2xx, 3xx, 4xx, 5xx)",
      "Compare HTTP/1.1 vs HTTP/2 vs HTTP/3",
      "Mention RESTful API design principles"
    ],
    tags: ["http", "web-protocols", "rest"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-9",
    question: "Explain routing algorithms (Distance Vector vs Link State)",
    category: "routing",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Distance Vector (like RIP): each router maintains distance table to all destinations, periodically shares entire table with neighbors, uses Bellman-Ford algorithm. Pros: simple implementation. Cons: slow convergence, count-to-infinity problem. Link State (like OSPF): each router maintains complete network topology, floods link state information, uses Dijkstra's algorithm locally. Pros: fast convergence, no loops. Cons: more complex, higher memory usage. Both aim to find shortest paths but differ in information sharing and computation approaches.",
    tips: [
      "Compare convergence speed and loop prevention",
      "Explain count-to-infinity problem",
      "Discuss scalability considerations",
      "Mention real protocols (RIP, OSPF, BGP)"
    ],
    tags: ["routing", "algorithms", "ospf", "rip"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-10",
    question: "What is ARP and how does it work?",
    category: "network-protocols",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "ARP (Address Resolution Protocol) maps IP addresses to MAC addresses on local networks. When a device needs to send data to an IP address on the same subnet: 1) Check ARP cache for existing mapping. 2) If not found, broadcast ARP request asking 'Who has this IP?'. 3) Device with that IP responds with ARP reply containing its MAC address. 4) Sender caches the mapping and uses MAC address for frame delivery. ARP is necessary because Ethernet uses MAC addresses for local delivery while applications use IP addresses.",
    tips: [
      "Explain why both IP and MAC addresses are needed",
      "Discuss ARP cache and timeout",
      "Mention security issues like ARP spoofing",
      "Compare with IPv6's Neighbor Discovery Protocol"
    ],
    tags: ["arp", "mac-address", "ip-address"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-11",
    question: "Explain different types of network topologies",
    category: "network-design",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Common topologies: 1) Bus: all devices connected to single cable, simple but single point of failure. 2) Star: all devices connected to central hub/switch, easy to manage but hub is bottleneck. 3) Ring: devices connected in circular fashion, equal access but failure breaks ring. 4) Mesh: devices interconnected, high reliability but expensive. 5) Tree/Hierarchical: combination of star topologies, scalable but dependent on root. 6) Hybrid: combination of multiple topologies. Choice depends on cost, reliability requirements, scalability needs, and management complexity.",
    tips: [
      "Discuss advantages and disadvantages of each",
      "Relate to real-world implementations",
      "Explain fault tolerance characteristics",
      "Consider cost and scalability factors"
    ],
    tags: ["topology", "network-design", "architecture"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-12",
    question: "What is VLAN and its benefits?",
    category: "switching",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "VLAN (Virtual Local Area Network) logically segments a physical network into multiple broadcast domains. Benefits: 1) Security: isolate sensitive traffic from general network. 2) Performance: reduce broadcast traffic by limiting broadcast domains. 3) Flexibility: group devices logically regardless of physical location. 4) Cost savings: use single switch for multiple logical networks. 5) Easier management: centralized VLAN configuration. VLANs are configured on managed switches using VLAN IDs (1-4094). Inter-VLAN communication requires routing through Layer 3 device.",
    tips: [
      "Explain broadcast domain concept",
      "Discuss VLAN tagging (802.1Q)",
      "Mention trunk vs access ports",
      "Compare with physical network segmentation"
    ],
    tags: ["vlan", "switching", "segmentation"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-13",
    question: "Explain the difference between hub, switch, and router",
    category: "network-devices",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Hub (Layer 1): repeats incoming signals to all ports, creates single collision domain, half-duplex, largely obsolete. Switch (Layer 2): learns MAC addresses, forwards frames only to intended recipient, each port is separate collision domain, full-duplex, maintains MAC address table. Router (Layer 3): routes packets between different networks using IP addresses, maintains routing table, provides network segmentation and security. Modern networks primarily use switches for LAN connectivity and routers for inter-network communication.",
    tips: [
      "Explain collision and broadcast domains",
      "Discuss MAC address learning in switches",
      "Compare half-duplex vs full-duplex",
      "Mention Layer 3 switches"
    ],
    tags: ["network-devices", "switching", "routing"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-14",
    question: "What is HTTPS and how does SSL/TLS work?",
    category: "security",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "HTTPS is HTTP over SSL/TLS, providing encrypted communication. SSL/TLS handshake process: 1) Client Hello: supported cipher suites, random number. 2) Server Hello: chosen cipher suite, certificate, random number. 3) Client verifies certificate, generates pre-master secret, encrypts with server's public key. 4) Both sides derive session keys from pre-master secret and random numbers. 5) Finished messages confirm handshake completion. Subsequent communication uses symmetric encryption with session keys. This provides confidentiality, integrity, and authentication.",
    tips: [
      "Explain asymmetric vs symmetric encryption usage",
      "Discuss certificate validation process",
      "Mention Perfect Forward Secrecy",
      "Compare SSL vs TLS versions"
    ],
    tags: ["https", "ssl", "tls", "encryption"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-15",
    question: "Explain IPv4 vs IPv6 differences",
    category: "ip-addressing",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "IPv4 uses 32-bit addresses (4.3 billion addresses), written in dotted decimal notation. IPv6 uses 128-bit addresses, written in hexadecimal with colons, providing virtually unlimited addresses. Key differences: 1) Address space: IPv6 solves IPv4 exhaustion. 2) Header: IPv6 has simpler, fixed-size header for faster processing. 3) Security: IPv6 has built-in IPSec support. 4) Auto-configuration: IPv6 supports stateless address auto-configuration. 5) No NAT needed: every device can have global address. 6) Quality of Service: better QoS support in IPv6. Transition mechanisms include dual-stack, tunneling, and translation.",
    tips: [
      "Compare address formats and sizes",
      "Explain IPv6 address types (unicast, multicast, anycast)",
      "Discuss transition challenges and mechanisms",
      "Mention IPv6 adoption status"
    ],
    tags: ["ipv4", "ipv6", "addressing"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-16",
    question: "How does Ethernet work and explain CSMA/CD",
    category: "data-link",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Ethernet is a data link layer protocol using CSMA/CD (Carrier Sense Multiple Access with Collision Detection) in traditional shared media: 1) Carrier Sense: listen before transmitting. 2) Multiple Access: multiple devices can access medium. 3) Collision Detection: detect when two stations transmit simultaneously. When collision detected, send jam signal, wait random backoff time (exponential backoff), then retry. Modern switched Ethernet eliminates collisions by providing dedicated bandwidth per port and enabling full-duplex communication.",
    tips: [
      "Explain exponential backoff algorithm",
      "Discuss minimum frame size requirements",
      "Compare shared vs switched Ethernet",
      "Mention Ethernet frame format"
    ],
    tags: ["ethernet", "csma-cd", "collision"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-17",
    question: "Explain how firewalls work and their types",
    category: "security",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Firewalls control network traffic based on security rules. Types: 1) Packet filtering: examines headers (IP, port, protocol), fast but limited. 2) Stateful inspection: tracks connection state, more secure than packet filtering. 3) Application layer: examines application data, can block specific content but slower. 4) Next-generation: combines multiple techniques with deep packet inspection, intrusion prevention, and application awareness. Firewalls can be hardware appliances, software-based, or cloud services. They implement default deny policies and allow specific traffic based on rules.",
    tips: [
      "Compare stateless vs stateful filtering",
      "Explain rule processing order",
      "Discuss DMZ and network segmentation",
      "Mention intrusion detection vs prevention"
    ],
    tags: ["firewall", "security", "packet-filtering"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-18",
    question: "What is load balancing and its algorithms?",
    category: "network-optimization",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Load balancing distributes incoming requests across multiple servers to improve performance, availability, and scalability. Algorithms: 1) Round Robin: requests distributed sequentially. 2) Weighted Round Robin: servers get requests proportional to their weights. 3) Least Connections: route to server with fewest active connections. 4) Weighted Least Connections: combines weights with connection count. 5) IP Hash: use client IP hash for consistent routing. 6) Random: distribute randomly. Health checks ensure traffic only goes to healthy servers. Can operate at Layer 4 (transport) or Layer 7 (application).",
    tips: [
      "Compare different algorithms and use cases",
      "Explain session persistence/sticky sessions",
      "Discuss health checking mechanisms",
      "Compare Layer 4 vs Layer 7 load balancing"
    ],
    tags: ["load-balancing", "scalability", "algorithms"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-19",
    question: "Explain CDN (Content Delivery Network) and its benefits",
    category: "network-optimization",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "CDN is a geographically distributed network of servers that cache and deliver content from locations closest to users. Benefits: 1) Reduced latency: content served from nearby edge servers. 2) Improved performance: faster load times and better user experience. 3) Reduced bandwidth costs: less traffic to origin servers. 4) High availability: redundancy across multiple locations. 5) DDoS protection: distributed architecture absorbs attacks. 6) Global reach: serve users worldwide efficiently. CDNs use techniques like caching policies, content replication, and intelligent routing.",
    tips: [
      "Explain edge server concept",
      "Discuss caching strategies and TTL",
      "Mention push vs pull CDN models",
      "Compare with traditional single-server approach"
    ],
    tags: ["cdn", "caching", "performance"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-20",
    question: "What is QoS (Quality of Service) in networking?",
    category: "network-management",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "QoS manages network resources to provide different service levels for different types of traffic. Key mechanisms: 1) Classification: identify traffic types using DSCP markings or port numbers. 2) Marking: tag packets with priority levels. 3) Queuing: use different queues for different traffic classes. 4) Scheduling: algorithms like Priority Queuing, Weighted Fair Queuing. 5) Shaping: control transmission rate. 6) Policing: enforce traffic contracts. QoS is crucial for real-time applications like VoIP, video conferencing, and streaming that require guaranteed bandwidth, low latency, and minimal jitter.",
    tips: [
      "Explain different QoS parameters (bandwidth, latency, jitter)",
      "Discuss traffic classification methods",
      "Compare different queuing algorithms",
      "Mention IntServ vs DiffServ models"
    ],
    tags: ["qos", "traffic-management", "priority"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-21",
    question: "Explain how VPN works",
    category: "security",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "VPN (Virtual Private Network) creates secure, encrypted tunnels over public networks. Types: 1) Site-to-Site: connects entire networks, typically using IPSec. 2) Remote Access: individual users connect to corporate network, often using SSL/TLS. Process: authentication (verify user identity), tunnel establishment (create encrypted channel), data transmission (encrypt all traffic through tunnel). Protocols include IPSec (network layer), SSL/TLS (application layer), and PPTP/L2TP (data link layer). VPNs provide confidentiality, integrity, and authentication while enabling secure remote access.",
    tips: [
      "Compare different VPN protocols",
      "Explain tunneling concept",
      "Discuss split-tunneling vs full-tunneling",
      "Mention performance considerations"
    ],
    tags: ["vpn", "security", "tunneling"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-22",
    question: "What is BGP and how does internet routing work?",
    category: "routing",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "BGP (Border Gateway Protocol) is the routing protocol of the internet, used between Autonomous Systems (AS). It's a path vector protocol that exchanges reachability information and AS path information. BGP speakers announce IP prefixes they can reach along with AS path (sequence of AS numbers). Route selection uses attributes like AS path length, local preference, origin type. BGP enables policy-based routing where organizations can control traffic flow based on business relationships (customer, peer, provider). It's designed for policy flexibility rather than optimal paths.",
    tips: [
      "Explain Autonomous System concept",
      "Discuss BGP attributes and route selection",
      "Mention internet peering relationships",
      "Compare with IGP protocols like OSPF"
    ],
    tags: ["bgp", "internet-routing", "autonomous-systems"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-23",
    question: "Explain network congestion control mechanisms",
    category: "performance",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "Congestion control prevents network collapse when demand exceeds capacity. TCP mechanisms: 1) Slow Start: exponentially increase congestion window until threshold. 2) Congestion Avoidance: linearly increase window after threshold. 3) Fast Retransmit: retransmit on 3 duplicate ACKs without waiting for timeout. 4) Fast Recovery: reduce window by half and continue in congestion avoidance. Network-level mechanisms include: Random Early Detection (RED) for proactive packet dropping, traffic shaping to smooth bursty traffic, and Quality of Service to prioritize important traffic.",
    tips: [
      "Explain TCP congestion window concept",
      "Discuss different congestion control algorithms",
      "Compare reactive vs proactive approaches",
      "Mention modern algorithms like BBR"
    ],
    tags: ["congestion-control", "tcp", "performance"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-24",
    question: "What is MPLS and its advantages?",
    category: "advanced-networking",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "MPLS (Multi-Protocol Label Switching) uses labels instead of IP addresses for forwarding decisions. Labels are inserted between Layer 2 and Layer 3 headers. Advantages: 1) Faster forwarding: simple label lookup vs complex IP routing table lookup. 2) Traffic engineering: explicit path control for optimal resource utilization. 3) VPN services: create isolated virtual networks over shared infrastructure. 4) QoS support: different service levels using label-based classification. 5) Protocol independence: works with various Layer 3 protocols. LSRs (Label Switch Routers) forward based on labels, while LERs (Label Edge Routers) add/remove labels at network edges.",
    tips: [
      "Explain label distribution protocols",
      "Discuss MPLS VPN services",
      "Compare with traditional IP routing",
      "Mention traffic engineering benefits"
    ],
    tags: ["mpls", "label-switching", "traffic-engineering"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-25",
    question: "Explain how SMTP works for email delivery",
    category: "application-protocols",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "SMTP (Simple Mail Transfer Protocol) handles email transmission between servers. Process: 1) Client connects to SMTP server on port 25. 2) HELO/EHLO: client identifies itself. 3) MAIL FROM: specify sender address. 4) RCPT TO: specify recipient address(es). 5) DATA: transmit email content. 6) QUIT: close connection. For email retrieval, clients use POP3 (download and delete) or IMAP (server-based storage). Modern email uses SMTP for sending, IMAP for accessing, with TLS encryption for security.",
    tips: [
      "Explain SMTP command sequence",
      "Compare POP3 vs IMAP for email retrieval",
      "Discuss email security (SPF, DKIM, DMARC)",
      "Mention relay and authentication requirements"
    ],
    tags: ["smtp", "email", "application-protocols"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-26",
    question: "What is network latency and how to minimize it?",
    category: "performance",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "Network latency is the time delay for data to travel from source to destination. Components: 1) Propagation delay: physical distance and medium speed. 2) Transmission delay: time to put data on wire. 3) Processing delay: router/switch processing time. 4) Queuing delay: waiting in buffers. Minimization strategies: 1) Reduce physical distance (CDNs, edge computing). 2) Use faster links and protocols. 3) Optimize routing paths. 4) Implement QoS for priority traffic. 5) Reduce packet size. 6) Use connection pooling and keep-alive. 7) Implement caching at multiple levels.",
    tips: [
      "Break down latency components",
      "Discuss measurement tools like ping and traceroute",
      "Explain jitter vs latency",
      "Compare WAN vs LAN latency characteristics"
    ],
    tags: ["latency", "performance", "optimization"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-27",
    question: "Explain the concept of network bandwidth and throughput",
    category: "performance",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "Bandwidth is the maximum data transmission capacity of a network link (theoretical limit), measured in bits per second. Throughput is the actual data transfer rate achieved in practice, always ≤ bandwidth due to protocol overhead, network congestion, and other factors. Factors affecting throughput: 1) Protocol overhead (headers, acknowledgments). 2) Network congestion and packet loss. 3) Latency and round-trip time. 4) Window size limitations in TCP. 5) Application efficiency. Bandwidth-delay product determines optimal window size for maximum throughput.",
    tips: [
      "Distinguish bandwidth from throughput clearly",
      "Explain factors that reduce throughput",
      "Discuss bandwidth-delay product",
      "Mention tools for measuring each"
    ],
    tags: ["bandwidth", "throughput", "performance"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-28",
    question: "What is ICMP and its common uses?",
    category: "network-protocols",
    difficulty: "easy",
    type: "technical",
    sampleAnswer: "ICMP (Internet Control Message Protocol) is a network layer protocol for error reporting and network diagnostics. Common uses: 1) Ping: Echo Request/Reply messages test reachability and measure round-trip time. 2) Traceroute: uses TTL expiration messages to trace packet path. 3) Error reporting: Destination Unreachable, Time Exceeded, Redirect messages. 4) Path MTU Discovery: helps determine maximum packet size. ICMP messages are encapsulated in IP packets but are considered part of IP layer functionality.",
    tips: [
      "Explain different ICMP message types",
      "Discuss security considerations (ICMP attacks)",
      "Show how ping and traceroute work",
      "Mention ICMPv6 differences"
    ],
    tags: ["icmp", "diagnostics", "error-reporting"],
    estimatedTime: 3,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-29",
    question: "Explain spanning tree protocol (STP) and its purpose",
    category: "switching",
    difficulty: "medium",
    type: "technical",
    sampleAnswer: "STP prevents loops in switched networks by creating a loop-free logical topology. Process: 1) Elect root bridge (lowest bridge ID). 2) Each non-root bridge finds shortest path to root. 3) Select root ports (best path to root) and designated ports (best path to each segment). 4) Block redundant ports to eliminate loops. When topology changes, STP reconverges. Variants include RSTP (Rapid STP) for faster convergence and MSTP (Multiple STP) for VLAN-aware operation. STP ensures broadcast storms don't occur while maintaining redundancy.",
    tips: [
      "Explain bridge ID and priority concepts",
      "Discuss port states (blocking, listening, learning, forwarding)",
      "Compare STP vs RSTP convergence times",
      "Mention alternatives like TRILL or SPB"
    ],
    tags: ["stp", "switching", "loop-prevention"],
    estimatedTime: 4,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
  {
    id: "cn-30",
    question: "What is SDN (Software Defined Networking) and its benefits?",
    category: "advanced-networking",
    difficulty: "hard",
    type: "technical",
    sampleAnswer: "SDN separates network control plane from data plane, centralizing network intelligence in software controllers. Architecture: 1) Application layer: network applications and services. 2) Control layer: centralized controllers with global network view. 3) Infrastructure layer: switches and routers that forward based on controller instructions. Benefits: 1) Centralized management and programmability. 2) Dynamic configuration and automation. 3) Vendor independence and innovation. 4) Better network utilization through global optimization. 5) Simplified troubleshooting with centralized view. OpenFlow is common southbound protocol between controller and switches.",
    tips: [
      "Explain control vs data plane separation",
      "Discuss OpenFlow protocol basics",
      "Compare with traditional networking",
      "Mention NFV (Network Function Virtualization) relationship"
    ],
    tags: ["sdn", "software-defined", "openflow"],
    estimatedTime: 5,
    industry: ["tech"],
    practiceCount: 0,
    successRate: 0,
  },
];
